version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6
  working_directory: ~/marquez_python_client_codegen

jobs:
  release:
    <<: *defaults
    working_directory: ~/marquez_python
    steps:
      - checkout
      - run: pip install --user twine
      - run: python setup.py sdist
      - run: python -m twine upload --verbose dist/*

workflows:
  version: 2
  marquez_python_client_codegen:
    jobs:
      - release:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
            branches:
              ignore: /.*/
